Add docker test

diff --git a/.github/workflows/dbt_ci.yml b/.github/workflows/dbt_ci.yml
--- a/.github/workflows/dbt_ci.yml
+++ b/.github/workflows/dbt_ci.yml
@@ -100,8 +100,15 @@ jobs:
 
     - name: Wait for Airflow health check
       run: |
-        until curl --fail http://localhost:8080/health; do
-          echo "Waiting for Airflow to be ready..."
+        max_retries=10  # Set a limit for the number of retries
+        retries=0
+        until curl --fail http://airflow-webserver:8080/health; do
+          if [ $retries -ge $max_retries ]; then
+            echo "Max retries reached, exiting..."
+            exit 1
+          fi
+          echo "Waiting for Airflow to be ready... (retry: $retries)"
+          retries=$((retries+1))
           sleep 10
         done
         
